# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

## Assignment 1

In [17]:
import numpy as np

# 1
arr = np.random.randint(1, 21, size=(5,5))
arr[:, 2] = 1
arr


array([[14, 16,  1, 18, 15],
       [ 1, 17,  1, 17,  9],
       [ 3,  8,  1,  6,  4],
       [18,  5,  1,  5, 20],
       [ 5,  2,  1, 14, 20]])

In [18]:
# 2
arr = np.arange(1, 17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Assignment 2

In [26]:
# 1
arr = np.arange(1, 37).reshape(6,6)
print("Original:")
arr

Original:


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [27]:
arr[2:5, 1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [34]:
# 2
print("Original:")
arr = np.random.randint(100000, size=(5,5))
arr

Original:


array([[ 4136, 71144, 67585,  8335, 34669],
       [18088, 98011, 42706, 98029, 93508],
       [80649, 19643, 53899, 56350, 87749],
       [18417, 47770, 28787,  7442, 34707],
       [98317,  4918, 74623, 98596, 85480]])

In [44]:
top_border = arr[0]
bottom_border = arr[-1]
left_border = arr[1:-1,0]
right_border = arr[1:-1,-1]
np.concatenate([top_border, left_border, bottom_border, right_border])

array([ 4136, 71144, 67585,  8335, 34669, 18088, 80649, 18417, 98317,
        4918, 74623, 98596, 85480, 93508, 87749, 34707])

## Assignment 3

In [46]:
# 1
arr1 = np.random.randint(1, 100, size=(3, 4))
arr2 = np.random.randint(1, 100, size=(3, 4))

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [[141  84  75 122]
 [130 127  99  38]
 [121  85 137  33]]
Subtraction: [[ 43   2 -35  26]
 [ 54  45  85 -30]
 [ 65 -49 -55  -7]]
Multiplication: [[4508 1763 1100 3552]
 [3496 3526  644  136]
 [2604 1206 3936  260]]
Division: [[ 1.87755102  1.04878049  0.36363636  1.54166667]
 [ 2.42105263  2.09756098 13.14285714  0.11764706]
 [ 3.32142857  0.26865672  0.42708333  0.65      ]]


In [52]:
# 2
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# row-wise sum
np.sum(arr, axis=1)

array([10, 26, 42, 58])

In [ ]:
#column-wise sum
np.sum(arr, axis=0)

array([28, 32, 36, 40])

## Assignment 4

In [ ]:
# 1
arr = np.random.randint(1,100, size=(5,5))

array([[86, 85, 70, 40, 66],
       [21, 19, 83, 44, 14],
       [95,  6, 12, 93, 98],
       [42, 60, 71, 18, 92],
       [54, 95, 68, 89, 12]])

In [61]:
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Mean: 8.5
Median: 8.5
Standard Deviation: 4.6097722286464435
Variance: 21.25


In [65]:
# 2
arr = np.arange(1, 10).reshape(3, 3)
print("Original:")
arr

Original:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
print("Normalized:")
arr = (arr - np.mean(arr)) / np.std(arr)
arr

Normalized:


array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

## Assignment 5

In [69]:
# 1
arr = np.random.randint(1,100, size=(3,3))
arr

array([[91, 99, 95],
       [32, 40,  2],
       [27, 41, 90]])

In [80]:
arr_to_add = np.arange(1, 4).reshape(1, 3)
arr_to_add

array([[1, 2, 3]])

In [81]:
arr + arr_to_add

array([[ 92, 101,  98],
       [ 33,  42,   5],
       [ 28,  43,  93]])

In [82]:
# 2
arr = np.random.randint(1, 100, size=(4,4))
arr

array([[14, 12, 21,  1],
       [92, 12, 38, 82],
       [10, 53, 78, 72],
       [26, 53, 19, 96]])

In [90]:
arr_to_subtract = np.random.randint(1, 100, size=(4,))
arr_to_subtract

array([28, 46, 45, 73])

In [91]:
arr - arr_to_subtract[:, np.newaxis]

array([[-14, -16,  -7, -27],
       [ 46, -34,  -8,  36],
       [-35,   8,  33,  27],
       [-47, -20, -54,  23]])

## Assignment 6

In [93]:
matrix = np.random.randint(1, 100, size=(3,3))
print("Original Matrix:")
matrix

Original Matrix:


array([[82, 55, 94],
       [56, 50, 19],
       [99, 18, 81]])

In [ ]:
# determinant
np.linalg.det(matrix)

-212516.99999999985

In [95]:
# Inverse
np.linalg.inv(matrix)

array([[-0.01744802,  0.01300131,  0.01719862],
       [ 0.01249312,  0.01253547, -0.0174386 ],
       [ 0.0185491 , -0.01867615, -0.00479962]])

In [96]:
# Eigenvalues
np.linalg.eigvals(matrix)

array([197.05258915, -25.82065174,  41.76806258])

In [105]:
# 2
matrix1 = np.arange(1,7).reshape(2,3)
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
matrix2 = np.arange(1,7)[::-1].reshape(3,2)
matrix2

array([[6, 5],
       [4, 3],
       [2, 1]])

In [107]:
np.dot(matrix1, matrix2)

array([[20, 14],
       [56, 41]])

## Assignment 7

In [ ]:
# 1
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [115]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# 2
arr = np.random.randint(1,100, size=(5,5))
arr

array([[97, 16,  4, 99, 99],
       [52,  9,  8, 93, 52],
       [57,  8, 17, 93, 46],
       [21, 13, 48, 60, 85],
       [63, 48, 93,  1, 69]])

In [121]:
arr = arr.flatten()
arr

array([97, 16,  4, 99, 99, 52,  9,  8, 93, 52, 57,  8, 17, 93, 46, 21, 13,
       48, 60, 85, 63, 48, 93,  1, 69])

In [123]:
arr.reshape(5,5)

array([[97, 16,  4, 99, 99],
       [52,  9,  8, 93, 52],
       [57,  8, 17, 93, 46],
       [21, 13, 48, 60, 85],
       [63, 48, 93,  1, 69]])

## Assignment 8

In [124]:
# 1
arr = np.random.randint(1, 100, size=(5,5))
arr


array([[20, 39, 25, 64, 60],
       [17, 60, 12, 68, 26],
       [54,  5, 43, 91, 82],
       [86, 79, 47, 73, 58],
       [73, 28,  9, 69,  4]])

In [126]:
corners = arr[[0, 0, -1, -1], [0, -1, -1, 0]]
corners

array([20, 60,  4, 73])

In [129]:
# 2
arr = np.random.randint(1, 100, size=(4,4))
print("Original:")
arr

Original:


array([[47, 70, 24, 19],
       [94,  1, 86, 74],
       [84, 83,  8, 18],
       [33, 30, 93, 57]])

In [130]:
arr[arr > 10] = 10
arr

array([[10, 10, 10, 10],
       [10,  1, 10, 10],
       [10, 10,  8, 10],
       [10, 10, 10, 10]])

## Assignment 9

In [140]:
# 1
data_type = [("name", 'U10'), ("age", 'i4'), ('weight', 'f4')]
data = [( 'James', 29, 78.8), ('Amelia', 28, 65.4), ('Olivia', 31, 68.9)]
data_arr = np.array(data, dtype = data_type)
data_arr

array([('James', 29, 78.8), ('Amelia', 28, 65.4), ('Olivia', 31, 68.9)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [141]:
np.sort(data_arr, order='age')

array([('Amelia', 28, 65.4), ('James', 29, 78.8), ('Olivia', 31, 68.9)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [148]:
# 2
data_type = [('x', 'i4'), ('y', 'i4')]
data = [(1, 2), (3, 4), (5, 6)]
data_arr = np.array(data, dtype=data_type)
data_arr

array([(1, 2), (3, 4), (5, 6)], dtype=[('x', '<i4'), ('y', '<i4')])

In [150]:
euc_dist = np.sqrt((data_arr['x'][:, np.newaxis] - data_arr['x'])**2 + (data_arr['y'][:, np.newaxis] - data_arr['y'])**2)
euc_dist

array([[0.        , 2.82842712, 5.65685425],
       [2.82842712, 0.        , 2.82842712],
       [5.65685425, 2.82842712, 0.        ]])

## Assignment 10

In [152]:
arr = np.random.randint(1, 30, size=(4, 4))
arr

array([[ 8, 23, 25, 26],
       [13, 25, 22, 21],
       [19,  8, 14, 18],
       [29, 24, 12, 18]])

In [153]:
masked_arr = np.ma.masked_greater(arr, 10)
masked_arr

masked_array(
  data=[[8, --, --, --],
        [--, --, --, --],
        [--, 8, --, --],
        [--, --, --, --]],
  mask=[[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True, False,  True,  True],
        [ True,  True,  True,  True]],
  fill_value=999999)

In [156]:
unmasked_sum = np.sum(masked_arr)
unmasked_sum

16

In [157]:
# 2
arr = np.random.randint(1, 30, size=(3, 3))
print(arr)

[[12 11  6]
 [14 10 12]
 [25 14 22]]


In [162]:
masked_arr = np.ma.masked_array(arr, mask=np.eye(3, dtype=bool))
masked_arr

masked_array(
  data=[[--, 11, 6],
        [14, --, 12],
        [25, 14, --]],
  mask=[[ True, False, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=999999)

In [165]:
masked_arr_mean = np.mean(masked_arr)
masked_arr_mean

13.666666666666666

In [166]:
masked_arr.filled(masked_arr_mean)


array([[13, 11,  6],
       [14, 13, 12],
       [25, 14, 13]])